### PR TITLE
Update version to v0.9.0

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by jakirkham** [comment]
AppVeyor somehow got broken w.r.t. this PR. Not sure why. Closing and reopening to try and retrigger.

**Comment by jakirkham** [comment]
Weird. That doesn't work either. Can you try pushing another commit here, @astrofrog? Potentially an empty one (e.g. `git commit --allow-empty -m 'Retrigger CI.'`).

**Comment by jakirkham** [comment]
Also please [re-render](https://github.com/conda-forge/conda-smithy/blob/master/README.md#re-rendering-an-existing-feedstock) with `conda-smithy`.

Edit: Or just merge PR ( https://github.com/conda-forge/glueviz-feedstock/pull/8 ) first.

**Comment by jakirkham** [comment]
Have managed to retrigger AppVeyor FYI. Think this was just an occurrence of issue ( https://github.com/appveyor/ci/issues/1002 ).

**Comment by astrofrog** [comment]
Since #8 had issues too, I've now cherry-picked #8 into here to trigger the CI

**Pull request merged**
